//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WJEntities : DbContext
    {
        public WJEntities()
            : base("name=WJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GuanLiYuan> GuanLiYuans { get; set; }
        public DbSet<QunZu> QunZus { get; set; }
        public DbSet<RenWu> RenWus { get; set; }
        public DbSet<WenJian> WenJians { get; set; }
        public DbSet<YongHu> YongHus { get; set; }
        public DbSet<YongHu_RenWu> YongHu_RenWu { get; set; }
    }
}
