//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenWu
    {
        public RenWu()
        {
            this.YongHu_RenWu = new HashSet<YongHu_RenWu>();
            this.WenJians = new HashSet<WenJian>();
        }
    
        public int ID { get; set; }
        public Nullable<int> YongHu_ID { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> UploadTime { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public string Publisher { get; set; }
        public Nullable<bool> Remark { get; set; }
        public string FilePath { get; set; }
        public string TaskDetails { get; set; }
        public Nullable<int> UnReaded { get; set; }
        public Nullable<int> UnFinished { get; set; }
    
        public virtual ICollection<YongHu_RenWu> YongHu_RenWu { get; set; }
        public virtual ICollection<WenJian> WenJians { get; set; }
        public virtual YongHu YongHu { get; set; }
    }
}
