//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class YongHu
    {
        public YongHu()
        {
            this.QunZus = new HashSet<QunZu>();
            this.RenWus = new HashSet<RenWu>();
            this.WenJians = new HashSet<WenJian>();
            this.YongHu_RenWu = new HashSet<YongHu_RenWu>();
            this.QunZus1 = new HashSet<QunZu>();
        }
    
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public Nullable<bool> State { get; set; }
        public string Password { get; set; }
        public int ID { get; set; }
        public string NickName { get; set; }
    
        public virtual ICollection<QunZu> QunZus { get; set; }
        public virtual ICollection<RenWu> RenWus { get; set; }
        public virtual ICollection<WenJian> WenJians { get; set; }
        public virtual ICollection<YongHu_RenWu> YongHu_RenWu { get; set; }
        public virtual ICollection<QunZu> QunZus1 { get; set; }
    }
}
