//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCZY
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStock
    {
        public InStock()
        {
            this.InStockDetails = new HashSet<InStockDetail>();
            this.PaidDetails = new HashSet<PaidDetail>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> Provider_ID { get; set; }
        public string ProviderName { get; set; }
        public Nullable<System.DateTime> InStockDate { get; set; }
        public string InStockState { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual ICollection<InStockDetail> InStockDetails { get; set; }
        public virtual ICollection<PaidDetail> PaidDetails { get; set; }
    }
}
