//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCZY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCZYEntities : DbContext
    {
        public SCZYEntities()
            : base("name=SCZYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChanPin_GongYingShang> ChanPin_GongYingShang { get; set; }
        public virtual DbSet<Consumer> Consumers { get; set; }
        public virtual DbSet<InStock> InStocks { get; set; }
        public virtual DbSet<InStockDetail> InStockDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderMoneyDetail> OrderMoneyDetails { get; set; }
        public virtual DbSet<PaidDetail> PaidDetails { get; set; }
        public virtual DbSet<ProduceInStock> ProduceInStocks { get; set; }
        public virtual DbSet<ProduceOutStock> ProduceOutStocks { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
