//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCZY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderMoneyDetails = new HashSet<OrderMoneyDetail>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> User_ID { get; set; }
        public decimal Consumer_ID { get; set; }
        public string ConsumerName { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> TakeDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Dispatch { get; set; }
        public Nullable<bool> Urgent { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Paid { get; set; }
        public string Remark { get; set; }
        public string OrderState { get; set; }
        public Nullable<double> AggregateAmount { get; set; }
    
        public virtual Consumer Consumer { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderMoneyDetail> OrderMoneyDetails { get; set; }
    }
}
