//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCZY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.ChanPin_GongYingShang = new HashSet<ChanPin_GongYingShang>();
            this.InStocks = new HashSet<InStock>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Remark { get; set; }
        public string Tel { get; set; }
        public string Company { get; set; }
    
        public virtual ICollection<ChanPin_GongYingShang> ChanPin_GongYingShang { get; set; }
        public virtual ICollection<InStock> InStocks { get; set; }
    }
}
